Models/ErrorViewModel.cs
namespace OnlineShop.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Login.cs
namespace OnlineShop.Models
{
    public class Login
    {
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Models;
using System.Diagnostics;

namespace OnlineShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OnlineShopController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Models;

namespace OnlineShop.Controllers
{
    public class OnlineShopController : Controller
    {
        public static List<Login> logins = new List<Login>();
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Registration()
        {
            var login = new Login();
            return View(login);
        }
        public IActionResult AboutUs()
        {
            return View();
        }
        public IActionResult Payment()
        {
            return View();
        }
        public IActionResult Comments()
        {
            return View();
        }
        public IActionResult NewAccount(Login login)
        {
            logins.Add(login);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult SignUp()
        {
            return View();
        }
        public IActionResult Administrator()
        {
            var admin= new Login();
            return View(admin);
        }
    }
}


Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/OnlineShop/AboutUs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!--  -->
<!-- <h1 class="align-content-center">Зв'яжіться з нами</h1>
 -->
<!-- <p>Наш магазин був створений в 2023 році, тобто лише почав своє існування. На даний момент в нашому асортименті доступні декілька
 -->
<!--     товарів, але ми плануємо розширювати його. Наш магазин пропонує вам широкий вибір товарів, які ви можете придбати за доступною ціною.
 -->
<!--
 -->
<!-- </p>
 -->
<!-- Compare this snippet from OnlineShop\Views\Shared\_Layout.cshtml: -->
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Про себе</title>

	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="~/css/styles.css" />
</head>

<body>
	@*<header>

	<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">

	<div class="container">
	</div>
	</header>*@
	<div>
		<h1 class="heading">Про нас</h1>
		<p>
			Наш магазин був створений в 2023 році, тобто лише почав своє існування. На даний момент в нашому асортименті доступні декілька
			товарів, але ми плануємо розширювати його. Наш магазин пропонує вам широкий вибір товарів, які ви можете придбати за доступною ціною.
		</p>
	</div>
</body>
</html>

Views/OnlineShop/Administrator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Login


<body class="registration">
	
	<div class="forma">
	<div class="reg-form">
		<h1 class="registration-header">Ще не зареєстровані? Створіть новий акаунт</h1>
		<form asp-controller="OnlineShop" asp-action="NewAccount" method="post" class="registration-form">
			<div class="mb-3">
				<label class="form-label">Ім'я користувача</label>
				<input asp-for=Username type="text" class="form-control" placeholder="Ім'я" />
			</div>
			<div class="mb-3">
				<label class="form-label">Пароль</label>
				<input asp-for=Password type="password" class="form-control" placeholder="Пароль" />
			</div>

			<div class="mb-3">
				<button type="submit" class="btn btn-primary">Підтвердити</button>

			</div>
			<h3 class="registration-text">Вже маєте акаунт?<a asp-controller="OnlineShop" asp-action="SignUp">Увійти</a></h3>
		</form>
	</div>
	</div>
	<div class="card-footer"></div>
</body>

Views/OnlineShop/Comments.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/OnlineShop/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE HTML>
<html>
<head>
	<title>OnlineShop</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!--<link rel="stylesheet" href="~/css/main.css" />-->
</head>
<body>
	<!-- Header -->
	<!-- Banner -->
	@*<section>*@
		<div class="home">
			<header class="heading">OnlineShop</header>
			@*<img href=""/>*@
			<div>
				<div>
					<h3>Самовивіз</h3>
					<p>Ви можете самостійно забрати товар з нашого магазину</p>
				</div>
				<div>
					<span class="icon fa-camera"></span>
					<h3>Доставка</h3>
					<p>Ми доставимо товар за адресою, яку ви вкажете</p>
				</div>
				<div>
					<span class="icon fa-bug"></span>
					<h3>Гарантія</h3>
					<p>Ми гарантуємо якість нашого товару</p>
				</div>
			</div>
		</div>
	@*</section>*@
</body>
</html>

Views/OnlineShop/Registration.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Login
<head>
	<title></title>
</head>
<body class="registration">
	
	<div class="forma">
	<div class="reg-form">
		<h1 class="registration-header">Ще не зареєстровані? Створіть новий акаунт</h1>
		<form asp-controller="OnlineShop" asp-action="NewAccount" method="post" class="registration-form">
			<div class="mb-3">
				<label class="form-label">Ел. пошта</label>
				<input asp-for=Email type="text" class="form-control" placeholder="Ел. пошта" />
			</div>
			<div class="mb-3">
				<label class="form-label">Ім'я користувача</label>
				<input asp-for=Username type="text" class="form-control" placeholder="Ім'я" />
			</div>
			<div class="mb-3">
				<label class="form-label">Пароль</label>
				<input asp-for=Password type="password" class="form-control" placeholder="Пароль" />
			</div>

			<div class="mb-3">
				<button type="submit" class="btn btn-primary">Підтвердити</button>

			</div>
			<h3 class="registration-text">Вже маєте акаунт?<a asp-controller="OnlineShop" asp-action="SignUp">Увійти</a></h3>
		</form>
	</div>
	</div>
	<div class="card-footer"></div>
</body>

Views/OnlineShop/SignUp.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Login



<body class="registration">
	
	<div class="forma">
	<div class="reg-form">
		<h1 class="registration-header">Ще не зареєстровані? Створіть новий акаунт</h1>
		<form asp-controller="OnlineShop" asp-action="NewAccount" method="post" class="registration-form">
			<div class="mb-3">
				<label class="form-label">Ім'я користувача</label>
				<input asp-for=Username type="text" class="form-control" placeholder="Ім'я" />
			</div>
			<div class="mb-3">
				<label class="form-label">Пароль</label>
				<input asp-for=Password type="password" class="form-control" placeholder="Пароль" />
			</div>

			<div class="mb-3">
				<button type="submit" class="btn btn-primary">Підтвердити</button>

			</div>
			<h3 class="registration-text">Вже маєте акаунт?<a asp-controller="OnlineShop" asp-action="SignUp">Увійти</a></h3>
		</form>
	</div>
	</div>
	<div class="card-footer"></div>
</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Магазин біжутерії</title>
	@* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/OnlineShop.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navigation-bar">
			<div class="container-fluid">
				<div class="navigator">
					<ul class="navig-ul">
						<li class="nav-item">
							<h2 class="shopn">Магазин біжутерії</h2>
						</li>
						<li class="nav-item">
							<a class="nav-lnk" asp-area="" asp-controller="OnlineShop" asp-action="Index">Домашня сторінка</a>
						</li>
						<li class="nav-item">
							<a class="nav-lnk" asp-area="" asp-controller="OnlineShop" asp-action="Payment">Доставка і оплата</a>
						</li>
						<li class="nav-item">
							<a class="nav-lnk" asp-area="" asp-controller="OnlineShop" asp-action="Comments">Відгуки</a>
						</li>
						<li class="nav-item">
							<a class="nav-lnk" asp-area="" asp-controller="OnlineShop" asp-action="AboutUs">Правила догляду</a>
						</li>
						<li class="nav-item">
							<a class="nav-lnk" asp-area="" asp-controller="OnlineShop" asp-action="Registration">Реєстрація/Вхід</a>
						</li>
						<li>
							<a class="nav-lnk" asp-area="" asp-controller="OnlineShop" asp-action="Administrator">Адміністратор</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">

		@RenderBody()

	</div>

	@*<footer class="border-bottom footer text-muted">
	<div class="container">
	&copy; 2023 - OnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
	</div>
	</footer>*@
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>